_default:
    @just -g --list

# update homebrew and then upgrade packages
brewupdg:
    @echo "\n🍺{{ BOLD + CYAN }} Updating Homebrew and upgrading packages...{{ NORMAL }}"
    brew update
    brew upgrade

# prune docker images, containers, volumes, and networks
docker-prune:
    @echo "🧼{{ BOLD + BLUE }} Pruning docker {{ INVERT }}images{{ NORMAL }}"
    docker image prune
    @echo "🧼{{ BOLD + BLUE }} Pruning docker {{ INVERT }}containers{{ NORMAL }}"
    docker container prune
    @echo "🧼{{ BOLD + BLUE }} Pruning docker {{ INVERT }}networks{{ NORMAL }}"
    docker network prune
    @echo "\n{{ BOLD + GREEN }}Docker images, containers, networks pruned successfully!{{ NORMAL }}"
    @echo "🐳{{ CYAN }} More info: https://docs.docker.com/engine/manage-resources/pruning/ {{ NORMAL }}"

# create bare git repo in the current directory and setup remote tracking
git-clone-bare GIT_URL:
    @echo "{{ BOLD + CYAN }}Cloning {{ GIT_URL }}{{ NORMAL }}"
    git clone --bare {{GIT_URL}} .bare
    echo "gitdir: ./.bare" > .git
    git config remote.origin.fetch '+refs/heads/*:refs/remotes/origin/*'
    @echo "\n{{ BOLD + GREEN }}Bare git repo set up successfully!{{ NORMAL }}" 

# update uv tools
uvx-up:
    @echo "\n⚡️{{ BOLD + MAGENTA }} Updating uv tools...{{ NORMAL }}"
    uv tool upgrade --all

# update global npm packages for bun and pnpm
npm-up:
    @echo "\n🤮{{ BOLD + YELLOW }} Updating bun and pnpm global packages...{{ NORMAL }}"
    bun update -g
    pnpm -g update --latest

# run updates for all tools
send-it:
    @echo "🗿{{ BOLD + CYAN }} Running updates for all tools...{{ NORMAL }}"
    @just -g brewupdg
    @just -g uvx-up
    @just -g npm-up
    @echo "\n✅{{ BOLD + GREEN }} All tools updated successfully!{{ NORMAL }}"
