[env]
NODE_ENV = 'production'

[tools]
go = "1.25"
usage = "latest"
zig = "0.15"
slsa-verifier = "latest"
minisign = "latest"
fnox = "latest"

[tasks.build]
run = 'echo "running build tasks"'

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
lockfile = false
python.uv_venv_auto = true

gpg_verify = true
trusted_config_paths = ["~/Code/*"]
disable_backends = ["ubi"]
