[env]
NODE_ENV = 'production'

[tools]
bat = "latest"
duckdb = "latest"
go = "1.24"
lazyjournal = "latest"
rust = "latest"
slsa-verifier = "latest"
terraform = "1.12.2"
usage = "latest"
zig = "0.14"
cosign = "latest"
cargo-binstall = "latest"

[tasks.build]
run = 'echo "running build tasks"'

[settings]
idiomatic_version_file_enable_tools = ["python", "node"]
