# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character] # The name of the module we are configuring is 'character'
# success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
success_symbol = '[󰚩](bold green)'
error_symbol = '[󱚟](bold red)'

[direnv]
disabled = false
format = '[$symbol$loaded $allowed]($style) '
symbol = ' '
allowed_msg = ''
not_allowed_msg = ''
denied_msg = ''
loaded_msg = 'loaded'
unloaded_msg = 'unloaded'
style = 'bold green'

[memory_usage]
disabled = false

[mise]
disabled = false
